### ISSUE TITLE
Spirograph Tool - producing square edges

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#84] opened 2020-09-17 05:01 UTC
If I hold the spirograph tool in one location for long enough it eventually fills in an area bounded by a square. Moving the tool also produces some unexpected straight edges. Behavior is the same across browsers. GIF will better illustrate:
![spirographSquareEdges](https://user-images.githubusercontent.com/48165321/93421886-6222f700-f867-11ea-9e47-929fbdccd797.gif)

**Comment by mudcube** [comment] 2020-11-24 23:25
Closing as duplicate of SketchIO/feedback-fall-2020#66

**Closed as completed by mudcube** 2020-11-24 23:25 UTC
Labels: Sketchpad
