### ISSUE TITLE
Layer Grouping causing elements to be hidden

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#81] opened 2020-09-16 23:37 UTC
Not sure if this is just a temporary issue but Sketchpad is currently hiding elements when I attempt to group them. The behavior is the same across browsers. If I toggle invisibility, the elements in the group display momentarily but quickly revert to being hidden. 
![layerGroupingCausesDisappearance](https://user-images.githubusercontent.com/48165321/93402882-cda29f80-f83a-11ea-8b76-593e9b6caa00.gif)

**Comment by mudcube** [comment] 2020-11-21 06:44
Closing as duplicate of #55

**Closed as completed by mudcube** 2020-11-21 06:44 UTC
Labels: Sketchpad
